workflows:
    hello-workspace:
        triggering:
            events:
                - push
            branch_patterns:
                - pattern: master
                  include: false
            cancel_previous_builds: true
        name: IOS Hello Pipeline
        scripts:
            - name: CI\CD Started
              script: echo "Welcome to your CI CD set up"
        publishing:
            email:
                recipients:
                    - adamyanlina97@gmail.com
